version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:7.10
      - image: circleci/postgres:9.6-alpine
          environment:
          - POSTGRES_DB: myinvestments-test
          - POSTGRES_USER: ""
          - POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run: 
          name: Add the Postgres 9.6 binaries to the path
          command: echo '/usr/lib/postgresql/9.6/bin/:$PATH' >> $BASH_ENV
      - run:
          name: Create database
          command: sudo psql -p 5433 -c 'create database myinvestments-test'
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build