version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.9.3
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_DB: myinvestments-test
          POSTGRES_USER: "user"
          POSTGRES_PASSWORD: "password"
    steps:
      - checkout
      - run:
          name: update yarn
          command: sudo npm install yarn@1.3.2 --global
      - restore_cache:
          key: v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: yarn install
      - save_cache:
          key: v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  lint:
    working_directory: ~/repo
    steps:
      - run:
          name: run linters
          command: yarn lint
  test:
    working_directory: ~/repo
    steps:
      - run:
          name: test
          command: yarn test --maxWorkers 2
      - run:
          name: generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build